# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: XplorersRekognition

custom:
  pythonRequirements:
    pythonBin: python

provider:
  name: aws
  runtime: python3.6

  stage: dev
#  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:SearchFacesByImage"
        - "rekognition:IndexFaces"
      Resource: "*"
    - Effect: "Allow"
      Action:
       - "s3:PutObject"
       - "s3:PutObjectAcl"
       - "s3:GetObject"
       - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${env:KNOWN_BUCKET_NAME}/*"
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource:
        - "arn:aws:sns:us-east-1:${env:AWS_ACCOUNT_NUMBER}:*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Describe*
      Resource:
        - "arn:aws:dynamodb:us-east-1:${env:AWS_ACCOUNT_NUMBER}:table/deeplens-known-faces"
        - "arn:aws:dynamodb:us-east-1:${env:AWS_ACCOUNT_NUMBER}:table/deeplens-unknown-faces"

# Environment Variables
  environment:
    BUCKET_NAME: ${env:UNKNOWN_BUCKET_NAME}
    KNOWN_BUCKET_NAME: ${env:KNOWN_BUCKET_NAME}
    UNKNOWN_BUCKET_NAME: ${env:UNKNOWN_BUCKET_NAME}
    SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
    SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
    SLACK_TRAINING_CHANNEL_ID: ${env:SLACK_TRAINING_CHANNEL_ID}
    REKOGNITION_COLLECTION_ID: ${env:REKOGNITION_COLLECTION_ID}
    SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}


package:
  exclude:
    - .c9/**
    - Notes
    - readme.md
    - license/**
    - Python-3.6.0/** # Excluded this directory generated by codebuild during installation of python3.6

resources:
  Resources:
    UnknownFacesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'deeplens-unknown-faces'
        AttributeDefinitions:
          - AttributeName: image_url
            AttributeType: S
        KeySchema:
          - AttributeName: image_url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    KnownFacesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'deeplens-known-faces'
        AttributeDefinitions:
          - AttributeName: user_name
            AttributeType: S
          - AttributeName: slack_user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_name
            KeyType: HASH
          - AttributeName: slack_user_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  guess:
    handler: handler.guess
    events:
      - s3:
          bucket: ${env:KNOWN_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
  unknown:
    handler: handler.unknown
    events:
      - s3:
          bucket: ${env:UNKNOWN_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: unknown/
  train:
    handler: handler.train
    events:
      - http:
          path: faces/train
          method: post

  # find person, function for greengrass device
  find-person:
    handler: find_person.function_handler
    runtime: python2.7
    role: arn:aws:iam::${env:AWS_ACCOUNT_NUMBER}:role/service-role/AWSDeepLensLambdaRole

plugins:
  - serverless-python-requirements
