# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: XplorersRekognition

custom:
  pythonRequirements:
    pythonBin: python

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
  stage: dev
#  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:SearchFacesByImage"
        - "rekognition:IndexFaces"
      Resource: "*"
    - Effect: "Allow"
      Action:
       - "s3:PutObject"
       - "s3:PutObjectAcl"
       - "s3:GetObject"
       - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${env:KNOWN_BUCKET_NAME}/*"

 #   - Effect: "Allow"
 #     Action:
 #       - "s3:ListBucket"
 #     Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
 #   - Effect: "Allow"
 #     Action:
 #       - "s3:PutObject"
 #     Resource:
 #       Fn::Join:
 #         - ""
 #         - - "arn:aws:s3:::"
 #           - "Ref" : "ServerlessDeploymentBucket"
 #           - "/*"

# you can define service wide environment variables here
  environment:
    BUCKET_NAME: ${env:KNOWN_BUCKET_NAME}
    SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
    SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
    SLACK_TRAINING_CHANNEL_ID: ${env:SLACK_TRAINING_CHANNEL_ID}
    REKOGNITION_COLLECTION_ID: ${env:REKOGNITION_COLLECTION_ID}


package:
  exclude:
    - .c9/
    - Notes
    - readme.md
    - license/
# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
resources:
  Resources:

    UnknownFacesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'unknown-faces'
        AttributeDefinitions:
          - AttributeName: RekognitionId
            AttributeType: S
        KeySchema:
          - AttributeName: RekognitionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    KnownFacesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'known-faces'
        AttributeDefinitions:
          - AttributeName: PersonId
            AttributeType: S
        KeySchema:
          - AttributeName: PersonId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  guess:
    handler: handler.guess
    events:
      - s3:
          bucket: ${env:KNOWN_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
  unknown:
    handler: handler.unknown
    events:
      - s3:
          bucket: ${env:KNOWN_BUCKET_NAME}
          event: s3:ObjectCreated:Copy
          rules:
            - prefix: unknown/
  train:
    handler: handler.train
    events:
      - http:
          path: faces/train
          method: post

  # find person, function for greengrass device
  find-person:
    handler: find_person.function_handler
    runtime: python2.7
    role: arn:aws:iam::${env:AWS_ACCOUNT_NUMBER}:role/service-role/AWSDeepLensLambdaRole

# resources:
#   Resources:
#     S3BucketDoormanfaces:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${env:BUCKET_NAME}
#         # add additional custom bucket configuration here
#
plugins:
  - serverless-python-requirements
