---
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with a public subnet for codebuild
Parameters:
  VPCName:
    Description: Name of vpc - dev, test, np, prd
    Type: String
    Default: dev
  CIDRVPC:
    Description: CIDR block for the entire VPC
    Type: String
    Default: 10.0.0.0/16
  CIDRPublicA:
    Description: CIDR block for Public Zone A
    Type: String
    Default: 10.0.0.0/24

Resources:
  NetworkStackParam:
    Type: AWS::SSM::Parameter
    Properties:
      Description: References the VPC stack name
      Type: String
      Name: '/network-stack'
      Value: !Sub '${AWS::StackName}'
  VPC:
    Description: The VPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref 'CIDRVPC'
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
      - Key: Name
        Value: !Sub "${VPCName}-VPC"
  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      CidrBlock: !Ref 'CIDRPublicA'
      AvailabilityZone: !Sub "${AWS::Region}a"
      Tags:
      - Key: Name
        Value: !Sub "${VPCName}-public-a"
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${VPCName}-igw"
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref 'InternetGateway'
      VpcId: !Ref 'VPC'
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
      - Key: Name
        Value: !Sub "${VPCName}-public"
  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref 'RouteTablePublic'
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref 'InternetGateway'
  SubnetRouteTableAssociationPublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'SubnetPublicA'
      RouteTableId: !Ref 'RouteTablePublic'
  NetworkAclPublic:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
      - Key: Name
        Value: !Sub "${VPCName}-NACL-public"
  NetworkAclEntryPublicInboundAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'NetworkAclPublic'
      RuleNumber: '100'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
  NetworkAclEntryPublicOutboundAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'NetworkAclPublic'
      RuleNumber: '100'
      Protocol: '-1'
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
  SubnetNetworkAclAssociationPublicA:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref 'SubnetPublicA'
      NetworkAclId: !Ref 'NetworkAclPublic'

Outputs:
  VPCID:
    Value: !Ref 'VPC'
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  VPCCIDR:
    Value: !Ref CIDRVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCCIDR"
  SubnetPublicA:
    Value: !Ref 'SubnetPublicA'
    Export:
      Name: !Sub "${AWS::StackName}-SubnetPublicA"
  VpcStackName:
    Value: !Sub "${AWS::StackName}"